### PR TITLE
6 develop visualrep / Adds visiaul elements

### PR DESCRIPTION
**Pull request by pontuslaestadius**
Adds the functioning aspects of the user story. 

Authors:
Sebastian, Pontus.

### CODE REVIEW

**Review by timjon — APPROVED** [review]
Need more comments

**Review by ghost — COMMENTED** [review]
The Main frame is scaling too big on windows OS

**Review by ghost — CHANGES_REQUESTED** [review]
please make the window size scalable

**Comment by pontuslaestadius** [comment]
@Rashadse A working version of scaling has been added. The performance will be improved later on.

**Review by ghost — APPROVED** [review]
the frame is very re-sizable and scalable now

**Review by timjon — CHANGES_REQUESTED** [review]
Please redo the pull request when you are done working

**Pull request closed without merging**
