### PR TITLE
improved animated background

### PR DESCRIPTION
**Pull request by ghost**
The improved animated background SkyGIF_2.0 has the following updates (use them as criteria for your review):
- moves in one direction only
- loops perfectly
- more frame

### CODE REVIEW

**Review by pontuslaestadius — DISMISSED** [review]
9.6 was completed last sprint?

These are all description points from the trello task so I'll use those to review it.

From a usability perspective it seem to 'jump' a bit - the jumping distracts from the animation of the sequence diagrams:
Still applies. In every frame. All of the clouds change size/position/are replaced? I can't even keep track of one cloud's location because the only way to do that is it's shape and that gets completely changed every single frame.

- mode intermediate steps ('between images') - so that there is not such a 'jump':
Why not just animate it the same way we are animating items on the canvas? (same request as last time it was made) 

- slower speed (as you tried):
This wouldn't fix the 'jump' issue though?

- finer resolution - this can also reduce the visual 'jumps':
The resolution is the same, more or less? Also it's square while the application will in most cases not be square.

**Comment by timjon** [comment]
- moves in one direction only
- I dont see the relation between this pull request and latency
- I would argue that there is more lag since the amount of frames increased and all of them seem laggy

**Review by ghost — COMMENTED** [review]
@timjon @pontuslaestadius 
Of course there could be many modifications to make the background 2.0 10 times better
The decided effort to improve the background this sprint only covered the following: 
- The user now isn't distracted by how version 1.0 was awkwardly looping back and forth every 2 seconds
- Each frame now is more tightly connected to the frame the precedes it and the frame that follows it. Version 1.0 had clouds suddenly popping up and disappearing! and that was the jumping issue

The final word on the background is the costumer's feedback next sprint review since this was a specific request by him.

**Comment by kosara-g** [comment]
I like it but it still "distracts", maybe make the clouds not change shape as much and just have them move one way in an infinite loop? have you tried emailing Michel or Michal with the new gif for a confirmation?

**Review by ghost — COMMENTED** [review]
@gusgolko 
i only worked on looping and adding more frames.
Waiting for costumer feedback at sprint review.

**Comment by kosara-g** [comment]
@Rashadse ok, that's fine by me

**Review by timjon — CHANGES_REQUESTED** [review]
The features that is supposed to be implemented is not implemented

**Comment by pontuslaestadius** [comment]
1. more frames
yes
2. one direction movement
no, Some are fading in from nowhere, a.k.a another direction.

3. perfect loop
I wouldn't know since they are modifying themselves in every frame so you can't track it.

do they cause any faults in the programme?
naming the file 2.0 wouldn't make any sense,  combining versioning with the file name would mean our java files would be Draw_2.1.java, 
Causing harder to change implementation as you have to tie source code to file version.

**Review by Sebastian-Fransson — COMMENTED** [review]
isn't one of the problems that it is a gif file? 
Isn't it supposed to be synced to the overall frame-rate of the application? 
What if the application frame-rate is changed? 
And didn't the customer want it to look smoother in terms of bit size like 16 instead of 8?

**Pull request closed without merging**
