### PR TITLE
Background update

### PR DESCRIPTION
**Pull request by ghost**
This is an attempt to approach the background issue before the release.

In this pull request:
-Muted the clouds as suggested by @gusgolko 
-Added more scenes to water waves

### CODE REVIEW

**Review by timjon — DISMISSED** [review]
Take it up during a meeting so we can discuss it

**Review by pontuslaestadius — APPROVED** [review]
Looks good.

**Review by kosara-g — CHANGES_REQUESTED** [review]
I'll approve this as soon as it's discussed on a meeting and added to trello. No other requests as of now.

**Comment by IsabelleTornqvist** [comment]
I don't see this in Trello

**Review by ghost — COMMENTED** [review]
I added this to trello and will bring it up next meeting

**Comment by kosara-g** [comment]
@Rashadse we've been here before; I appreciate your circumstances but you can't just go ahead with stuff on your own; come on, you know better than this

**Review by kosara-g — APPROVED** [review]

**Pull request merged**
